name: Pull Request BUILD


on:
    pull_request:
      branches: [master]
      types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        dotnet: ["2.1.x", "2.2.x", "3.0.x", "3.1.x"]
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
    - name: Installing .NET Core ${{matrix.dotnet}}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{matrix.dotnet}}
    - run: |
        dotnet clean && dotnet nuget locals all --clear
        dotnet restore
    - name: Building
      run: dotnet build --no-restore
    - name: Testing
      run: cd Jitex.Tests
    - name: Testing Debug
      run: dotnet test -c Debug
    - name: Testing Release
      run: dotnet test -c Release
